arena-file-path: "plugins/blockparty/levels.json"
stats-file-path: "plugins/blockparty/stats.json"
world-name: "world"
power-up-chance-denominator: "3"
special-round-chance-denominator: "2"
lobby-check-initial-delay-seconds: "15"
lobby-check-interval-seconds: "5"
lobby-game-start-seconds: "31"
