name: Blockparty
version: 1.0.0
main: org.pine.blockparty.Blockparty
description: Blockparty minigame
author: PaperMC
website: https://papermc.io
api-version: '1.21.3'
commands:
  bpstart:
    description: Start the game
    usage: /bpstart
  bpstop:
      description: Stop the game
      usage: /bpstop
  bplvlinfo:
    description: Gives information about the enabled levels
    usage: /bplvlinfo
  bplvl:
    description: Changes the map to the specified level
    usage: /bplvl
