name: Blockparty
version: 1.0.0
main: org.pine.Blockparty
description: Blockparty minigame
author: PaperMC
website: https://papermc.io
api-version: '1.21.3'
commands:
  bpstart:
    description: Start the game
    usage: /bpstart
  bplvlinfo:
    description: Gives information about the enabled levels
    usage: /bplvlinfo
