name: Blockparty
version: 1.1
main: org.pine.blockparty.Blockparty
description: Blockparty minigame
author: Pine
api-version: '1.21.4'

commands:
  bpstart:
    description: Start the game
    usage: /bpstart
  bpstop:
      description: Stop the game
      usage: /bpstop
  bplvlinfo:
    description: Show level information
    usage: /bplvlinfo
  bplvl:
    description: Changes the map to the specified level
    usage: /bplvl <levelName>
  bpfw:
    description: Starts the fireworks show
    usage: /bpfw

permissions:
  blockparty.admin:
    description: Allows admin control of the game
    default: op
