name: Blockparty
version: 1.1
main: org.pine.blockparty.Blockparty
description: Blockparty minigame
author: Pine
api-version: '1.21.4'

commands:
  bphelp:
    description: Instructions
    usage: /bphelp
  bpstats:
    description: Show your statistics
    usage: /bpstats
  bpspec:
    description: Spectate instead of playing
    usage: /bpspec
  bpstart:
    description: Start the game
    usage: /bpstart
    permission: blockparty.admin
  bpstop:
    description: Stop the game
    usage: /bpstop
    permission: blockparty.admin
  bplvlinfo:
    description: Show level information
    usage: /bplvlinfo
    permission: blockparty.admin
  bplvl:
    description: Changes the map to the specified level
    usage: /bplvl <levelName>
    permission: blockparty.admin
  bpfw:
    description: Starts the fireworks show
    usage: /bpfw
    permission: blockparty.admin
  bppower:
    description: Spawn a power-up
    usage: /bppower
    permission: blockparty.admin

permissions:
  blockparty.admin:
    description: Allows admin control of the game
    default: op
