package org.pine.model;

public enum GameState {

    IDLE,
    STARTING_FIRST_ROUND,
    CHANGE_PLATFORM,
    SHOW_XBLOCK,
    XBLOCK_REMOVAL,
    ROUND_EVALUATION,
    UPDATE_DIFFICULTY,
    WIN_CONDITION_WINNER,
    WIN_CONDITION_TIE,
    WIN_CONDITION_ROUND_END,
    GAME_OVER
}
